---

- hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: ansible_os_family == 'Debian'
    - name: Create common config directory
      file:
        path: "{{ common_directory_config }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
  roles:
    - role: calvinbui.ansible_nfs_client
    - role: calvinbui.ansible_docker
    - role: calvinbui.ansible_pip
    - role: calvinbui.ansible_docker_network
    - role: calvinbui.ansible_htpasswd
    - role: calvinbui.ansible_traefik
    - role: calvinbui.ansible_nzbget_docker
    - role: calvinbui.ansible_qbittorrent_docker
    - role: calvinbui.ansible_sonarr_docker
    - role: calvinbui.ansible_couchpotato_docker
    - role: calvinbui.ansible_nzbhydra_docker
    - role: calvinbui.ansible_jdownloader_docker
    - role: calvinbui.ansible_organizr_docker
    - role: calvinbui.ansible_portainer
    - role: calvinbui.ansible_watchtower
