---

couchpotato_name: couchpotato
couchpotato_image: linuxserver/couchpotato
couchpotato_ports:
  - 5050:5050
couchpotato_config_directory: "{{ common_directory_config }}/couchpotato"
couchpotato_movie_directory: "{{ common_directory_movies }}"
couchpotato_download_directory: "{{ common_directory_download }}"
couchpotato_environment_variables:
  PUID: "{{ common_user_id }}"
  PGID: "{{ common_user_group }}"
  TZ: "{{ common_timezone }}"

couchpotato_docker_additional_options:
  restart_policy: unless-stopped
  networks: "{{ docker_networks }}"
  labels:
    traefik.frontend.rule: "Host:{{ couchpotato_name }}.{{ common_tldr }}"
    traefik.port: "{{ couchpotato_ports[0].split(':')[0] }}"

couchpotato_config:
  core.dark_theme: 1
  core.launch_browser: 0
  core.dereferrer: ""
  core.show_wizard: 0
  manage.library_refresh_interval: 24
  manage.cleanup: 0
  manage.enabled: 1
  manage.library: /movies/
  renamer.file_name: <thename><cd>.<quality>.<group>.<ext>
  renamer.nfo_name: <filename>.<ext>
  renamer.cleanup: 1
  renamer.enabled: 1
  renamer.unrar: 1
  subtitle.languages: en
  subtitle.enabled: 1
  trailer.enabled: 1
  blackhole.enabled: 0
  nzbget.enabled: 1
  transmission.enabled: 1
  kickasstorrents.enabled: 0
  torrentz.enabled: 0
  searcher.preferred_method: nzb
  imdb.chart_display_top250: 1
  imdb.chart_display_theater: 1
  moviesearcher.cron_hour: 8
  moviesearcher.cron_minute: 15
