---

couchpotato_name: couchpotato
couchpotato_image: linuxserver/couchpotato
couchpotato_ports:
  - 5050:5050
couchpotato_config_directory: "{{ common_directory_config }}/couchpotato"
couchpotato_movie_directory: "{{ common_directory_movies }}"
couchpotato_download_directory: "{{ common_directory_download }}"
couchpotato_environment_variables:
  PUID: "{{ common_user_id }}"
  PGID: "{{ common_root_group }}"
  TZ: "{{ common_timezone }}"

couchpotato_docker_additional_options:
  restart_policy: unless-stopped
  networks: "{{ docker_networks }}"
  labels:
    traefik.frontend.rule: "Host:{{ couchpotato_name }}.{{ common_tldr }}"
    traefik.port: "{{ couchpotato_ports[0].split(':')[0] }}"

couchpotato_config:
  core.dereferer: ""
  core.dark_theme: 1
  core.launch_browser: 0
  core.show_wizard: 0
  manage.library_refresh_interval: 24
  manage.cleanup: 'False'
  manage.enabled: 'True'
  manage.library: /movies/
  renamer.file_name: <thename><cd>.<quality>.<group>.<ext>
  renamer.nfo_name: <filename>.<ext>
  renamer.from: /downloads/Movies/
  renamer.to: /movies/
  renamer.cleanup: 'True'
  renamer.enabled: 'True'
  renamer.unrar: 'True'
  subtitle.languages: en
  subtitle.enabled: 'True'
  trailer.enabled: 'True'
  blackhole.enabled: 'False'
  nzbget.enabled: 1
  nzbget.host: "{{ nzbget_name }}.{{ docker_networks[0].name }}:{{ nzbget_ports[0].split(':')[0] }}"
  transmission.enabled: 'False'
  email.starttls: 1
  email.smtp_pass: "{{ common_email_password }}"
  email.from: "{{ common_email_username }}"
  email.to: "couchpotato{{ common_email_to }}"
  email.smtp_port: "{{ common_email_smtp_port }}"
  email.enabled: 1
  email.smtp_server: "{{ common_email_server }}"
  email.smtp_user: "{{ common_email_username }}"
  newznab.use: 1
  newznab.extra_score: ''
  newznab.host: "{{ nzbhydra_name }}.{{ docker_networks[0].name }}:{{ nzbhydra_ports[0].split(':')[0] }}"
  newznab.custom_tag: ''
  newznab.api_key: ''
  kickasstorrents.enabled: 'False'
  torrentz.enabled: 'False'
  searcher.preferred_method: nzb
  nzb.retention: "{{ nzbget_config['Server1.Retention'] }}"
