---

nzbhydra_name: nzbhydra
nzbhydra_image: linuxserver/hydra2
nzbhydra_ports:
  - 5076:5076
nzbhydra_config_directory: "{{ common_directory_config }}/nzbhydra"
nzbhydra_download_directory: "{{ common_directory_download }}"
nzbhydra_environment_variables:
  PUID: "{{ common_user_id }}"
  PGID: "{{ common_root_group }}"
  TZ: "{{ common_timezone }}"

nzbhydra_docker_additional_options:
  restart_policy: unless-stopped
  labels:
    traefik.frontend.rule: "Host:{{ nzbhydra_name }}.{{ common_tldr }}"
    traefik.port: "{{ nzbhydra_ports[0].split(':')[0] }}"

nzbhydra_config:
  main.dereferer: ""
  main.logging.logIpAddresses: "false"
  main.startupBrowser: "false"
  main.verifySsl: "false"
  main.welcomeShown: "true"
