---

portainer_name: portainer
portainer_image: portainer/portainer
portainer_ports:
  - 9000:9000
portainer_config_directory: "{{ common_directory_config }}/portainer"

portainer_docker_additional_options:
  restart_policy: unless-stopped
  networks: "{{ docker_networks }}"
  command: '--no-auth --no-analytics'
