---

traefik_name: traefik
traefik_image: traefik:1.7.11-alpine
traefik_config_template: traefik.toml.j2
traefik_config_directory: "{{ common_directory_config }}/traefik/"
traefik_ports:
  - 8080:8080  # management
  - 80:80  # http
  - 443:443  # https

traefik_docker_additional_options:
  restart_policy: always
  networks: "{{ docker_networks }}"
